const words = [
    // --- ANIMALS ---
    { word: "ELEPHANT", hint: "O maior animal terrestre.", translation: "Elefante", category: "Animais" },
    { word: "GIRAFFE", hint: "Tem o pescoço muito longo.", translation: "Girafa", category: "Animais" },
    { word: "LION", hint: "O rei da selva.", translation: "Leão", category: "Animais" },
    { word: "TIGER", hint: "Um felino grande e listrado.", translation: "Tigre", category: "Animais" },
    { word: "BEAR", hint: "Pode ser pardo, polar ou panda.", translation: "Urso", category: "Animais" },
    { word: "ZEBRA", hint: "Parece um cavalo listrado.", translation: "Zebra", category: "Animais" },
    { word: "MONKEY", hint: "Adora bananas e árvores.", translation: "Macaco", category: "Animais" },
    { word: "KANGAROO", hint: "Animal australiano que pula.", translation: "Canguru", category: "Animais" },
    { word: "PENGUIN", hint: "Ave que não voa e vive no gelo.", translation: "Pinguim", category: "Animais" },
    { word: "DOLPHIN", hint: "Mamífero marinho muito inteligente.", translation: "Golfinho", category: "Animais" },
    { word: "SHARK", hint: "Predador dos oceanos.", translation: "Tubarão", category: "Animais" },
    { word: "WHALE", hint: "O maior animal do mundo.", translation: "Baleia", category: "Animais" },
    { word: "EAGLE", hint: "Símbolo de liberdade nos EUA.", translation: "Águia", category: "Animais" },
    { word: "OWL", hint: "Ave noturna sábia.", translation: "Coruja", category: "Animais" },
    { word: "BUTTERFLY", hint: "Inseto colorido que já foi lagarta.", translation: "Borboleta", category: "Animais" },
    { word: "SPIDER", hint: "Tem oito pernas e tece teias.", translation: "Aranha", category: "Animais" },
    { word: "SNAKE", hint: "Réptil sem pernas que rasteja.", translation: "Cobra", category: "Animais" },
    { word: "TURTLE", hint: "Carrega a casa nas costas.", translation: "Tartaruga", category: "Animais" },
    { word: "FROG", hint: "Anfíbio verde que pula.", translation: "Sapo", category: "Animais" },
    { word: "RABBIT", hint: "Orelhudo que gosta de cenoura.", translation: "Coelho", category: "Animais" },

    // --- TECHNOLOGIA ---
    { word: "COMPUTER", hint: "Máquina usada para processar dados.", translation: "Computador", category: "Tecnologia" },
    { word: "KEYBOARD", hint: "Usado para digitar.", translation: "Teclado", category: "Tecnologia" },
    { word: "MOUSE", hint: "Usado para mover o cursor.", translation: "Mouse", category: "Tecnologia" },
    { word: "SCREEN", hint: "Onde você vê as imagens.", translation: "Tela", category: "Tecnologia" },
    { word: "INTERNET", hint: "Rede mundial de computadores.", translation: "Internet", category: "Tecnologia" },
    { word: "SOFTWARE", hint: "Programas e aplicativos.", translation: "Software", category: "Tecnologia" },
    { word: "DATABASE", hint: "Onde dados são armazenados.", translation: "Banco de Dados", category: "Tecnologia" },
    { word: "ROBOT", hint: "Máquina programável automática.", translation: "Robô", category: "Tecnologia" },
    { word: "SMARTPHONE", hint: "Telefone celular inteligente.", translation: "Smartphone", category: "Tecnologia" },
    { word: "TABLET", hint: "Computador portátil com tela de toque.", translation: "Tablet", category: "Tecnologia" },
    { word: "CAMERA", hint: "Tira fotos e grava vídeos.", translation: "Câmera", category: "Tecnologia" },
    { word: "BATTERY", hint: "Fonte de energia portátil.", translation: "Bateria", category: "Tecnologia" },
    { word: "CHARGER", hint: "Recarrega a bateria.", translation: "Carregador", category: "Tecnologia" },
    { word: "HEADPHONES", hint: "Usado para ouvir música nos ouvidos.", translation: "Fones de Ouvido", category: "Tecnologia" },
    { word: "MICROPHONE", hint: "Captopta som.", translation: "Microfone", category: "Tecnologia" },

    // --- ALIMENTOS ---
    { word: "APPLE", hint: "Fruta proibida no Éden.", translation: "Maçã", category: "Alimentos" },
    { word: "BANANA", hint: "Fruta amarela e curva.", translation: "Banana", category: "Alimentos" },
    { word: "ORANGE", hint: "Fruta cítrica e uma cor.", translation: "Laranja", category: "Alimentos" },
    { word: "GRAPE", hint: "Usada para fazer vinho.", translation: "Uva", category: "Alimentos" },
    { word: "STRAWBERRY", hint: "Fruta vermelha com sementes fora.", translation: "Morango", category: "Alimentos" },
    { word: "WATERMELON", hint: "Fruta grande, verde fora e vermelha dentro.", translation: "Melancia", category: "Alimentos" },
    { word: "PINEAPPLE", hint: "Fruta tropical com coroa.", translation: "Abacaxi", category: "Alimentos" },
    { word: "TOMATO", hint: "Fruta vermelha usada em saladas.", translation: "Tomate", category: "Alimentos" },
    { word: "POTATO", hint: "Tubérculo usado para fazer fritas.", translation: "Batata", category: "Alimentos" },
    { word: "CARROT", hint: "Legume laranja que o coelho gosta.", translation: "Cenoura", category: "Alimentos" },
    { word: "BREAD", hint: "Feito de farinha e assado.", translation: "Pão", category: "Alimentos" },
    { word: "CHEESE", hint: "Derivado do leite, o rato adora.", translation: "Queijo", category: "Alimentos" },
    { word: "CHICKEN", hint: "Ave comum na culinária.", translation: "Frango", category: "Alimentos" },
    { word: "BEEF", hint: "Carne de vaca.", translation: "Carne Bovina", category: "Alimentos" },
    { word: "FISH", hint: "Carne branca de animal aquático.", translation: "Peixe", category: "Alimentos" },
    { word: "RICE", hint: "Grão branco base da alimentação oriental.", translation: "Arroz", category: "Alimentos" },
    { word: "PASTA", hint: "Massa italiana como espaguete.", translation: "Macarrão", category: "Alimentos" },
    { word: "PIZZA", hint: "Disco de massa com recheio.", translation: "Pizza", category: "Alimentos" },
    { word: "BURGER", hint: "Sanduíche de carne.", translation: "Hambúrguer", category: "Alimentos" },
    { word: "CHOCOLATE", hint: "Doce feito de cacau.", translation: "Chocolate", category: "Alimentos" },
    { word: "ICE CREAM", hint: "Doce gelado de leite.", translation: "Sorvete", category: "Alimentos" },
    { word: "COFFEE", hint: "Bebida escura e energizante.", translation: "Café", category: "Alimentos" },
    { word: "JUICE", hint: "Líquido extraído de frutas.", translation: "Suco", category: "Alimentos" },
    { word: "WATER", hint: "Líquido essencial para a vida.", translation: "Água", category: "Alimentos" },

    // --- VIAGEM ---
    { word: "AIRPLANE", hint: "Veículo que voa.", translation: "Avião", category: "Viagem" },
    { word: "PASSPORT", hint: "Documento para viagens internacionais.", translation: "Passaporte", category: "Viagem" },
    { word: "SUITCASE", hint: "Onde você leva suas roupas.", translation: "Mala", category: "Viagem" },
    { word: "TICKET", hint: "Bilhete que permite a entrada.", translation: "Passagem/Ingresso", category: "Viagem" },
    { word: "HOTEL", hint: "Lugar onde se paga para dormir.", translation: "Hotel", category: "Viagem" },
    { word: "BEACH", hint: "Lugar com areia e mar.", translation: "Praia", category: "Viagem" },
    { word: "MOUNTAIN", hint: "Grande elevação de terra.", translation: "Montanha", category: "Viagem" },
    { word: "TRAIN", hint: "Veículo que anda sobre trilhos.", translation: "Trem", category: "Viagem" },
    { word: "BUS", hint: "Transporte coletivo rodoviário.", translation: "Ônibus", category: "Viagem" },
    { word: "MAP", hint: "Desenho de uma região geográfica.", translation: "Mapa", category: "Viagem" },
    { word: "CAMERA", hint: "Para registrar, memórias.", translation: "Câmera", category: "Viagem" },
    { word: "GUIDE", hint: "Pessoa que mostra o caminho.", translation: "Guia", category: "Viagem" },
    { word: "SUBWAY", hint: "Trem subterrâneo.", translation: "Metrô", category: "Viagem" },
    { word: "AIRPORT", hint: "Onde os aviões pousam.", translation: "Aeroporto", category: "Viagem" },

    // --- PROFISSÕES ---
    { word: "DOCTOR", hint: "Cuida dos doentes.", translation: "Médico", category: "Profissões" },
    { word: "TEACHER", hint: "Ensina alunos na escola.", translation: "Professor", category: "Profissões" },
    { word: "ENGINEER", hint: "Projeta e constrói coisas.", translation: "Engenheiro", category: "Profissões" },
    { word: "LAWYER", hint: "Defende as pessoas na lei.", translation: "Advogado", category: "Profissões" },
    { word: "CHEF", hint: "Cozinheiro profissional.", translation: "Chefe de Cozinha", category: "Profissões" },
    { word: "POLICE", hint: "Protege a cidade.", translation: "Polícia", category: "Profissões" },
    { word: "FIREFIGHTER", hint: "Apaga incêndios.", translation: "Bombeiro", category: "Profissões" },
    { word: "SCIENTIST", hint: "Faz experimentos e descobertas.", translation: "Cientista", category: "Profissões" },
    { word: "ARTIST", hint: "Cria arte.", translation: "Artista", category: "Profissões" },
    { word: "WRITER", hint: "Escreve livros.", translation: "Escritor", category: "Profissões" },
    { word: "PILOT", hint: "Pilota aviões.", translation: "Piloto", category: "Profissões" },
    { word: "NURSE", hint: "Assiste o médico e pacientes.", translation: "Enfermeiro", category: "Profissões" },
    { word: "ACTOR", hint: "Atua em filmes ou teatro.", translation: "Ator", category: "Profissões" },
    { word: "DRIVER", hint: "Dirige um veículo.", translation: "Motorista", category: "Profissões" },
    { word: "FARMER", hint: "Trabalha na fazenda.", translation: "Fazendeiro", category: "Profissões" },

    // --- NATUREZA ---
    { word: "TREE", hint: "Planta grande com tronco.", translation: "Árvore", category: "Natureza" },
    { word: "FLOWER", hint: "Parte colorida da planta.", translation: "Flor", category: "Natureza" },
    { word: "RIVER", hint: "Fluxo de água doce.", translation: "Rio", category: "Natureza" },
    { word: "OCEAN", hint: "Grande massa de água salgada.", translation: "Oceano", category: "Natureza" },
    { word: "FOREST", hint: "Muitas árvores juntas.", translation: "Floresta", category: "Natureza" },
    { word: "RAIN", hint: "Água que cai do céu.", translation: "Chuva", category: "Natureza" },
    { word: "SUN", hint: "Estrela do nosso sistema.", translation: "Sol", category: "Natureza" },
    { word: "MOON", hint: "Satélite natural da Terra.", translation: "Lua", category: "Natureza" },
    { word: "STAR", hint: "Ponto brilhante no céu noturno.", translation: "Estrela", category: "Natureza" },
    { word: "CLOUD", hint: "Massa branca no céu.", translation: "Nuvem", category: "Natureza" },
    { word: "WIND", hint: "Ar em movimento.", translation: "Vento", category: "Natureza" },
    { word: "SNOW", hint: "Cristais de gelo do céu.", translation: "Neve", category: "Natureza" },
    { word: "FIRE", hint: "Produz calor e luz.", translation: "Fogo", category: "Natureza" },
    { word: "STONE", hint: "Material duro da terra.", translation: "Pedra", category: "Natureza" },

    // --- CASA ---
    { word: "HOUSE", hint: "Lugar onde se mora.", translation: "Casa", category: "Casa" },
    { word: "WINDOW", hint: "Abertura na parede para ver fora.", translation: "Janela", category: "Casa" },
    { word: "DOOR", hint: "Entrada da casa.", translation: "Porta", category: "Casa" },
    { word: "KITCHEN", hint: "Onde se prepara comida.", translation: "Cozinha", category: "Casa" },
    { word: "BEDROOM", hint: "Onde se dorme.", translation: "Quarto", category: "Casa" },
    { word: "BATHROOM", hint: "Onde se toma banho.", translation: "Banheiro", category: "Casa" },
    { word: "TABLE", hint: "Móvel para apoiar coisas.", translation: "Mesa", category: "Casa" },
    { word: "CHAIR", hint: "Móvel para sentar.", translation: "Cadeira", category: "Casa" },
    { word: "BED", hint: "Móvel para deitar.", translation: "Cama", category: "Casa" },
    { word: "SOFA", hint: "Cadeira grande e confortável.", translation: "Sofá", category: "Casa" },
    { word: "LAMP", hint: "Objeto que ilumina.", translation: "Abajur/Lâmpada", category: "Casa" },
    { word: "FRIDGE", hint: "Mantém a comida gelada.", translation: "Geladeira", category: "Casa" },

    // --- CORPO HUMANO ---
    { word: "HEAD", hint: "Onde fica o cérebro.", translation: "Cabeça", category: "Corpo Humano" },
    { word: "HAND", hint: "Tem cinco dedos.", translation: "Mão", category: "Corpo Humano" },
    { word: "FOOT", hint: "Usado para andar.", translation: "Pé", category: "Corpo Humano" },
    { word: "EYE", hint: "Usado para ver.", translation: "Olho", category: "Corpo Humano" },
    { word: "EAR", hint: "Usado para ouvir.", translation: "Orelha/Ouvido", category: "Corpo Humano" },
    { word: "NOSE", hint: "Usado para cheirar.", translation: "Nariz", category: "Corpo Humano" },
    { word: "MOUTH", hint: "Usada para comer e falar.", translation: "Boca", category: "Corpo Humano" },
    { word: "HEART", hint: "Bombeia o sangue.", translation: "Coração", category: "Corpo Humano" },
    { word: "BRAIN", hint: "Controla o corpo.", translation: "Cérebro", category: "Corpo Humano" },
    { word: "LEG", hint: "Membro inferior.", translation: "Perna", category: "Corpo Humano" },
    { word: "ARM", hint: "Membro superior.", translation: "Braço", category: "Corpo Humano" },

    // --- PERSONALIDADES ---
    { word: "EINSTEIN", hint: "Físico da Teoria da Relatividade.", translation: "Einstein", category: "Personalidades" },
    { word: "SHAKESPEARE", hint: "Escritor de Romeu e Julieta.", translation: "Shakespeare", category: "Personalidades" },
    { word: "DA VINCI", hint: "Pintor da Mona Lisa.", translation: "Da Vinci", category: "Personalidades" },
    { word: "MANDELA", hint: "Líder sul-africano contra o apartheid.", translation: "Mandela", category: "Personalidades" },
    { word: "CLEOPATRA", hint: "Rainha do Egito Antigo.", translation: "Cleópatra", category: "Personalidades" },
    { word: "MOZART", hint: "Compositor austríaco prodígio.", translation: "Mozart", category: "Personalidades" },
    { word: "GANDHI", hint: "Líder pacifista da Índia.", translation: "Gandhi", category: "Personalidades" },
    { word: "JOBS", hint: "Fundador da Apple.", translation: "Steve Jobs", category: "Personalidades" },
    { word: "PELE", hint: "O Rei do Futebol.", translation: "Pelé", category: "Personalidades" },
    { word: "SENNA", hint: "Piloto brasileiro ídolo da F1.", translation: "Ayrton Senna", category: "Personalidades" },

    // --- ESPORTES ---
    { word: "SOCCER", hint: "O esporte mais popular do mundo.", translation: "Futebol", category: "Esportes" },
    { word: "BASKETBALL", hint: "Jogado com as mãos e uma cesta.", translation: "Basquete", category: "Esportes" },
    { word: "VOLLEYBALL", hint: "Jogado com uma rede alta.", translation: "Vôlei", category: "Esportes" },
    { word: "TENNIS", hint: "Usa raquetes e uma bola amarela.", translation: "Tênis", category: "Esportes" },
    { word: "SWIMMING", hint: "Esporte na água.", translation: "Natação", category: "Esportes" },
    { word: "RUNNING", hint: "Correr rápido.", translation: "Corrida", category: "Esportes" },
    { word: "BOXING", hint: "Luta com luvas.", translation: "Boxe", category: "Esportes" },
    { word: "GOLF", hint: "Esporte de acertar a bola no buraco.", translation: "Golfe", category: "Esportes" },

    // --- VERBOS ---
    { word: "RUN", hint: "Mover-se rápido a pé.", translation: "Correr", category: "Verbos" },
    { word: "EAT", hint: "Ingerir alimentos.", translation: "Comer", category: "Verbos" },
    { word: "SLEEP", hint: "Descansar à noite.", translation: "Dormir", category: "Verbos" },
    { word: "DRINK", hint: "Ingerir líquidos.", translation: "Beber", category: "Verbos" },
    { word: "READ", hint: "Interpretar palavras escritas.", translation: "Ler", category: "Verbos" },
    { word: "WRITE", hint: "Colocar palavras no papel.", translation: "Escrever", category: "Verbos" },
    { word: "SPEAK", hint: "Usar a voz para comunicar.", translation: "Falar", category: "Verbos" },
    { word: "LISTEN", hint: "Usar os ouvidos.", translation: "Ouvir", category: "Verbos" },
    { word: "WALK", hint: "Mover-se devagar a pé.", translation: "Andar", category: "Verbos" },
    { word: "PLAY", hint: "Se divertir ou competir.", translation: "Brincar/Jogar", category: "Verbos" },
    { word: "WORK", hint: "Realizar uma tarefa profissional.", translation: "Trabalhar", category: "Verbos" },
    { word: "STUDY", hint: "Aprender algo novo.", translation: "Estudar", category: "Verbos" }
];
