const words = [
    { word: "ELEPHANT", hint: "O maior animal terrestre.", translation: "Elefante" },
    { word: "COMPUTER", hint: "Máquina usada para trabalho e jogos.", translation: "Computador" },
    { word: "BUTTERFLY", hint: "Inseto colorido que voa.", translation: "Borboleta" },
    { word: "sky", hint: "A atmosfera vista da terra.", translation: "Céu" },
    { word: "beach", hint: "Lugar com areia e mar.", translation: "Praia" },
    { word: "mountain", hint: "Grande elevação natural da terra.", translation: "Montanha" },
    // Personalidades
    { word: "EINSTEIN", hint: "Físico famoso pela teoria da relatividade.", translation: "Albert Einstein" },
    { word: "SHAKESPEARE", hint: "Famoso dramaturgo e poeta inglês.", translation: "William Shakespeare" },
    { word: "DA VINCI", hint: "Pintor da Mona Lisa e polímata renascentista.", translation: "Leonardo da Vinci" },
    { word: "MANDELA", hint: "Líder anti-apartheid e presidente da África do Sul.", translation: "Nelson Mandela" },
    { word: "CLEOPATRA", hint: "Última rainha ativa do Reino Ptolemaico do Egito.", translation: "Cleópatra" },
    { word: "MOZART", hint: "Compositor prolífico e influente da era clássica.", translation: "Wolfgang Amadeus Mozart" },
    { word: "GANDHI", hint: "Liderou a independência da Índia por meios não violentos.", translation: "Mahatma Gandhi" },
    { word: "JOBS", hint: "Co-fundador da Apple e visionário da tecnologia.", translation: "Steve Jobs" },
    { word: "DANGEROUS", hint: "Algo que oferece risco ou perigo.", translation: "Perigoso" },
    { word: "BEAUTIFUL", hint: "Qualidade do que é belo.", translation: "Bonito(a)" },
    { word: "HAPPINESS", hint: "Sentimento de alegria e bem-estar.", translation: "Felicidade" },
    { word: "CHOCOLATE", hint: "Doce feito de cacau.", translation: "Chocolate" },
    { word: "ADVENTURE", hint: "Experiência emocionante e arriscada.", translation: "Aventura" },
    { word: "KNOWLEDGE", hint: "O que se adquire com o estudo.", translation: "Conhecimento" },
    { word: "YESTERDAY", hint: "O dia anterior a hoje.", translation: "Ontem" },
    { word: "BREAKFAST", hint: "A primeira refeição do dia.", translation: "Café da manhã" },
    { word: "RAINBOW", hint: "Arco colorido que aparece após a chuva.", translation: "Arco-íris" },
    { word: "LIBRARY", hint: "Lugar onde se guardam livros.", translation: "Biblioteca" },
    { word: "VACATION", hint: "Período de descanso do trabalho ou escola.", translation: "Férias" },
    { word: "FRIENDSHIP", hint: "Relação de afeto entre amigos.", translation: "Amizade" },
    { word: "CHAMPION", hint: "Vencedor de uma competição.", translation: "Campeão" },
    { word: "WONDERFUL", hint: "Algo maravilhoso, fantástico.", translation: "Maravilhoso" }
];
